services:
  - type: web
    name: project-manager
    env: docker
    plan: free
    branch: main
    disk:
      name: data
      mountPath: /app/server/data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 3000
      - key: BOARD_TENDERS
        value: b_tenders
      - key: IMAP_HOST
        sync: false
      - key: IMAP_PORT
        sync: false
      - key: IMAP_SECURE
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: GOOGLE_SCRIPT_URL
        sync: false
      # Members
      - key: IMAP_USER_MONTSE
        sync: false
      - key: IMAP_PASS_MONTSE
        sync: false
      - key: IMAP_USER_NEUS
        sync: false
      - key: IMAP_PASS_NEUS
        sync: false
      - key: IMAP_USER_ALBA
        sync: false
      - key: IMAP_PASS_ALBA
        sync: false
      - key: IMAP_USER_ATEIXIDO
        sync: false
      - key: IMAP_PASS_ATEIXIDO
        sync: false
      - key: IMAP_USER_OMAR
        sync: false
      - key: IMAP_PASS_OMAR
        sync: false
      - key: IMAP_USER_WEB
        sync: false
      - key: IMAP_PASS_WEB
        sync: false
      - key: IMAP_USER_INES
        sync: false
      - key: IMAP_PASS_INES
        sync: false
      - key: IMAP_USER_COMPTABILITAT
        sync: false
      - key: IMAP_PASS_COMPTABILITAT
        sync: false
      - key: IMAP_USER_LICITACIONS
        sync: false
      - key: IMAP_PASS_LICITACIONS
        sync: false
      - key: IMAP_USER_GESTIO
        sync: false
      - key: IMAP_PASS_GESTIO
        sync: false
      - key: IMAP_USER_TEST
        sync: false
      - key: IMAP_PASS_TEST
        sync: false
